site_name: LCRC User Guide
nav:
  - Home: index.md
  - Account and Project Management:
    - Accounts and Access: account-project-management/accounts-and-access.md
    - Managing Projects: account-project-management/project-management.md
    - SSH: account-project-management/ssh.md
  - Allocations:
    - Allocations on LCRC Computing Resources: allocation-management/allocations.md
    - lcrc-sbank Allocation Accounting System (Slurm Clusters): allocation-management/lcrc-sbank-allocation-accounting-system.md
    - sbank Allocation Accounting System (PBS Clusters): allocation-management/sbank-allocation-accounting-system.md
  #- Running Jobs with Slurm at LCRC:
  #  - Overview:
  - Running Jobs at LCRC:
    - Overview: running-jobs-at-lcrc/overview.md
    - Running Jobs on PBS Pro Clusters: running-jobs-at-lcrc/pbs-pro-clusters.md
    - Running Jobs on Slurm Clusters: running-jobs-at-lcrc/slurm-clusters.md
    - Using Software:
      - Getting Started: using-software/getting-started.md 
      - Software-Specific Guides: 
        - Conda: using-software/software-specific-guides/conda.md
        - Jupyter Notebooks: using-software/software-specific-guides/jupyter-notebooks.md
        - Paraview: using-software/software-specific-guides/paraview.md
        - Tensorflow: using-software/software-specific-guides/tensorflow.md
  - Data Management:
    - Data Transfer:
      - SFTP and SCP: data-management/data-transfer/sftp-scp.md
      - Using Globus: data-management/data-transfer/using-globus.md
    - File System & Storage:
      - File Systems: data-management/filesystem-and-storage/file-systems.md
      - Data Storage: data-management/filesystem-and-storage/data-storage.md
      - Disk Quota: data-management/filesystem-and-storage/disk-quota.md
  - Improv:
    - Getting Started: improv/getting-started-improv.md
    - Hardware Overview: improv/hardware-overview-improv.md
    - Running Jobs on Improv: improv/running-jobs-improv.md
  - Swing:
    - Getting Started: swing/getting-started-swing.md
    - Hardware Overview: swing/hardware-overview-swing.md
    - Running Jobs on Swing: swing/running-jobs-swing.md
  - Bebop:
    - Getting Started: bebop/getting-started-bebop.md
    - Hardware Overview: bebop/hardware-overview-bebop.md
    - Running Jobs on Bebop: bebop/running-jobs-bebop.md
  - Best Practices and Policies:
    - Best Practices and Policies Overview: best-practices-and-policies/best-practices-and-policies-overview.md
    - Allocations Expiration Policy: best-practices-and-policies/allocation-expiration-policy.md
    - Cybersecurity Policy: best-practices-and-policies/cybersecurity-policy.md
    - Data Policy: best-practices-and-policies/data-policy.md
    - Job Scheduling Policy: best-practices-and-policies/job-scheduling-policy.md
    - Monthly Maintenance Day: best-practices-and-policies/monthly-maintenance-day.md
    - Reservation Policy: best-practices-and-policies/reservation-policy.md
    - Shared Resource Policy: best-practices-and-policies/shared-resource-policy.md
    - SSH Policy: best-practices-and-policies/ssh-policy.md
not_in_nav: |
  not_in_nav/
theme:
  name: 'material'
  custom_dir: overrides
  language: 'en'
  palette:
    scheme: alcf
  font:
    text: proxima-nova
  features:
    - tabs
    - instant
    - search.highlight
    - search.suggest
  logo: 'images/Argonne_wireframe_white_transparent.png'
  favicon: 'images/alcf_favicon.ico'

extra_css:
  - stylesheets/alcf-extra.css

extra_javascript:
  - javascripts/alcf-extra.js

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

repo_name: 'argonne-lcrc/user-guides'
repo_url: 'https://github.com/argonne-lcrc/user-guides'
site_url: 'https://argonne-lcrc.github.io/user-guides'

extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/argonne-lcrc/user-guides'

plugins:
  - search
