site_name: LCRC User Guide
nav:
  - Home: index.md
  - Account and Project Management:
    - Accounts and Access: account-project-management/accounts-and-access.md
    - Managing Projects: account-project-management/project-management.md
    - Allocations:
      - Allocations on LCRC Computing Resources: account-project-management/allocation-management/overview.md
      - Managing Your Allocations: account-project-management/allocation-management/allocation-management.md
      - lcrc-sbank Allocation Accounting System (Slurm Clusters): account-project-management/allocation-management/lcrc-sbank-allocation-accounting-system.md
      - sbank Allocation Accounting System (PBS Clusters): account-project-management/allocation-management/sbank-allocation-accounting-system.md
  - Data Management:
    - Data Transfer:
      - SFTP and SCP: data-management/data-transfer/sftp-scp.md
      - Using Globus: data-management/data-transfer/using-globus.md
    - File System & Storage:
      - File Systems: data-management/filesystem-and-storage/file-systems.md
      - Data Storage: data-management/filesystem-and-storage/data-storage.md
      - Disk Quota: data-management/filesystem-and-storage/disk-quota.md
not_in_nav: |
  not_in_nav/
theme:
  name: 'material'
  custom_dir: overrides
  language: 'en'
  palette:
    scheme: alcf
  font:
    text: proxima-nova
  features:
    - tabs
    - instant
    - search.highlight
    - search.suggest
  logo: 'images/Argonne_wireframe_white_transparent.png'
  favicon: 'images/alcf_favicon.ico'

extra_css:
  - stylesheets/alcf-extra.css

extra_javascript:
  - javascripts/alcf-extra.js

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

repo_name: 'argonne-lcrc/user-guides'
repo_url: 'https://github.com/argonne-lcrc/user-guides'
site_url: 'https://argonne-lcrc.github.io/user-guides'

extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/argonne-lcrc/user-guides'

plugins:
  - search
